// <auto-generated />
using System;
using HistoClassAI.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HistoClassAI.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260824195125_SeedTissus")]
    partial class SeedTissus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HistoClassAI.Api.Models.Choix", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("EstCorrect")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Texte")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Choix");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            EstCorrect = true,
                            QuestionId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Texte = "Protection contre l'abrasion"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            EstCorrect = false,
                            QuestionId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Texte = "Absorption des nutriments"
                        });
                });

            modelBuilder.Entity("HistoClassAI.Api.Models.Organe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrlImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Organes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Nom = "Épiderme",
                            UrlImage = ""
                        });
                });

            modelBuilder.Entity("HistoClassAI.Api.Models.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Texte")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TissuId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TissuId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Texte = "Quelle est la principale fonction de l'épithélium stratifié ?",
                            TissuId = new Guid("22222222-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("HistoClassAI.Api.Models.ResultatQCM", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateTest")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Note")
                        .HasColumnType("integer");

                    b.Property<Guid>("ScanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ScanId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("ResultatsQCM");
                });

            modelBuilder.Entity("HistoClassAI.Api.Models.Scan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateScan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("ScoreConfiance")
                        .HasColumnType("real");

                    b.Property<Guid>("TissuId")
                        .HasColumnType("uuid");

                    b.Property<string>("UrlImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TissuId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Scans");
                });

            modelBuilder.Entity("HistoClassAI.Api.Models.Tissu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodeLabelIa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fonctions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CodeLabelIa")
                        .IsUnique();

                    b.ToTable("Tissus");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CodeLabelIa = "classe_04",
                            Description = "Tissu formé de plusieurs couches de cellules.",
                            Fonctions = "Protection contre l'abrasion.",
                            Nom = "Épithélium Stratifié"
                        });
                });

            modelBuilder.Entity("HistoClassAI.Api.Models.TissuOrgane", b =>
                {
                    b.Property<Guid>("TissuId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganeId")
                        .HasColumnType("uuid");

                    b.HasKey("TissuId", "OrganeId");

                    b.HasIndex("OrganeId");

                    b.ToTable("TissuOrganes");

                    b.HasData(
                        new
                        {
                            TissuId = new Guid("22222222-2222-2222-2222-222222222222"),
                            OrganeId = new Guid("33333333-3333-3333-3333-333333333333")
                        });
                });

            modelBuilder.Entity("HistoClassAI.Api.Models.Utilisateur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Utilisateurs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            DateCreation = new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "prof@ensat.ma",
                            MotDePasseHash = "admin123",
                            Nom = "Professeur",
                            Prenom = "Admin",
                            Role = "Professeur"
                        });
                });

            modelBuilder.Entity("HistoClassAI.Api.Models.Choix", b =>
                {
                    b.HasOne("HistoClassAI.Api.Models.Question", "Question")
                        .WithMany("Choix")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("HistoClassAI.Api.Models.Question", b =>
                {
                    b.HasOne("HistoClassAI.Api.Models.Tissu", "Tissu")
                        .WithMany("Questions")
                        .HasForeignKey("TissuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tissu");
                });

            modelBuilder.Entity("HistoClassAI.Api.Models.ResultatQCM", b =>
                {
                    b.HasOne("HistoClassAI.Api.Models.Scan", "Scan")
                        .WithMany("ResultatsQCM")
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HistoClassAI.Api.Models.Utilisateur", "Utilisateur")
                        .WithMany("ResultatsQCM")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scan");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("HistoClassAI.Api.Models.Scan", b =>
                {
                    b.HasOne("HistoClassAI.Api.Models.Tissu", "Tissu")
                        .WithMany("Scans")
                        .HasForeignKey("TissuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HistoClassAI.Api.Models.Utilisateur", "Utilisateur")
                        .WithMany("Scans")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tissu");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("HistoClassAI.Api.Models.TissuOrgane", b =>
                {
                    b.HasOne("HistoClassAI.Api.Models.Organe", "Organe")
                        .WithMany("TissuOrganes")
                        .HasForeignKey("OrganeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HistoClassAI.Api.Models.Tissu", "Tissu")
                        .WithMany("TissuOrganes")
                        .HasForeignKey("TissuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organe");

                    b.Navigation("Tissu");
                });

            modelBuilder.Entity("HistoClassAI.Api.Models.Organe", b =>
                {
                    b.Navigation("TissuOrganes");
                });

            modelBuilder.Entity("HistoClassAI.Api.Models.Question", b =>
                {
                    b.Navigation("Choix");
                });

            modelBuilder.Entity("HistoClassAI.Api.Models.Scan", b =>
                {
                    b.Navigation("ResultatsQCM");
                });

            modelBuilder.Entity("HistoClassAI.Api.Models.Tissu", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Scans");

                    b.Navigation("TissuOrganes");
                });

            modelBuilder.Entity("HistoClassAI.Api.Models.Utilisateur", b =>
                {
                    b.Navigation("ResultatsQCM");

                    b.Navigation("Scans");
                });
#pragma warning restore 612, 618
        }
    }
}
